sudo: required

language: swift

services:
  - docker

script:
  - docker build -t jinw1990/iswift.linux:travis

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jinw1990/iswift.linux:travis;
    fi
